version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.7"
  jobs:
    post_build:
      - echo "sed -i 's/GeneratedClient/Client/g' docs/build/html/index.html"

sphinx:
   configuration: docs/source/conf.py

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: requirements.txt